### ISSUE TITLE
Issue with 'Required options not defined: urlAuthorize, urlAccessToken, urlResourceOwnerDetails'

### ISSUE THREAD

**Issue by pascalvgemert** [robertogallea/restado#1]
When following the instructions, I get the following error:

![image](https://user-images.githubusercontent.com/1567379/33781079-80143aea-dc53-11e7-8768-489a92f80200.png)

When I add the following code to the `getProvider` method, I get an `Invalid Scope` error:

```
'urlAuthorize' => 'https://my.tado.com/oauth/token', 
'urlAccessToken' => 'https://my.tado.com/oauth/token', 
'urlResourceOwnerDetails' => null,
```

Then adding `'scope' => 'home.user',` to the `authorize` method (below password), it seems to be working again.

**Comment by robertogallea** [comment]
Hi @pascalvgemert, in what method do you encounter problems? 

Try the following:
1) Have you defined TADO_USER and TADO_PASS in your env.
2) Have you tried the following?
$token = Restado::authorize();
$me = Restado::me($token);

Please let me know if you manage to use the service.

**Comment by robertogallea** [comment]
Ok, I tried what you pointed out, urlAuthorize that was a previously non-required option, or something changed in the Tado API. Howver, I included your suggesteions and updated the package to version 1.0.2

Thank you.
