### ISSUE TITLE
switch to new tado authentication server

### ISSUE THREAD

**Issue by elmi82** [robertogallea/restado#2]
tado is discontinuing the old OAuth2 endpoints at `my.tado.com`. Starting March 2019, authentication will require retrieving access and refresh tokens from `auth.tado.com`. The client `public-api-preview` can be used as is (with the same client secret) on the new endpoint.

The new authentication will also be a standard OAuth2 system, but will use JWT as a format for refresh tokens. So be aware that this will increase the size of the refresh tokens.

Additionally, the new endpoints implement [refresh token rotation](https://tools.ietf.org/html/rfc6749#section-10.4). A new refresh token is issued with every access token refresh response. The previous refresh token is invalidated.

**Comment by robertogallea** [comment]
Thank you for pointing it out. I just switched to the new endpoint

**Comment by macrosak** [comment]
@robertogallea unfortunately the fix in  22a204599469c00f6d6458f21be1047cb81b3d13 is not correct.

Only the *authorization* server has changed (`auth.tado.com`). The *resource* server remains the same (`my.tado.com`).

If I read the code correctly, only `urlAuthorize` and `urlAccessToken` should change:

https://github.com/robertogallea/restado/blob/22a204599469c00f6d6458f21be1047cb81b3d13/src/Restado.php#L681-L682

Furthermore, the `urlAuthorize` URL should be `https://auth.tado.com/oauth/authorize`

**Comment by robertogallea** [comment]
Again,
thank you for your feedback. I was lazy and I didn't do the required modifications, until now that it stopped working ;)

It should be ok now.
