### ISSUE TITLE
New API route: zoneStates (plural)

### ISSUE THREAD

**Issue by trevtb** [robertogallea/restado#22]
Hello and thank you very much for your API! :)

I noticed that it is now possible to get all zone states with a single request by using the following route:

'https://my.tado.com/api/v2/homes/' . $home_id . '/zoneStates',

This way one does not have to send a request for each room which is very useful.

I added the following function to Restado.php:

 ```php

/**
     * @param $access_token
     * @param $home_id
     * @return mixed
     */
    public function getHomeZoneStates($access_token, $home_id) {
        $provider = $this->getProvider();

        $request = $provider->getAuthenticatedRequest(
            'GET',
            'https://my.tado.com/api/v2/homes/' . $home_id . '/zoneStates',
            $access_token
        );
        $client = new \GuzzleHttp\Client();
        $response = $client->send($request);
        return json_decode($response->getBody());
    }
```

Could you include it in your repository?

**Comment by robertogallea** [comment]
Hi! Thank you for your addition! the method has been added and the repo has been already merged!

Next time you can proceed to make a PR yourself. Thanks again!
